[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
ebpf_program = "CPy4XsWvCfZyjjfx3Uymf2y6BfN7vUHczb9dLYmPvSJc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/gubasso/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
